### ISSUE TITLE
Bugs, features and improvements

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#186]
- [x] 1. Speed dialda bulunan request sayfaları hala eskileri. Onları yeni sayfalar ile güncellemeliyiz. (fix: #165)

- [x] 2. Bildirim açma checkbox'ı açılmasına rağmen uygulama kapatıp açmadan checked olmuyor. (Bu durum açık olmasına rağmen açmaya yönlendiriyor) (fix: #165)

- [x] 3. Ana ekranda aşağı scroll edince arama yukarı scroll ederken gözükmüyor, sliver appbar kullanımı veya home tab seçili iken tekrar home tab’e tıklanırsa en yukarı scroll edebiliriz (https://github.com/VB-CORE/life_client/pull/190)

- [x] 4. Kategori seçiminde en sondaki item seçilince detayda en altta gözüküyor, detaydaki kategori alanı ilk etapta scrollable gözükmediği için seçim yokmuş gibi anlaşılabilir, scrollable bir alanmış gibi scroll çubuğu ekleyebiliriz veya seçili elemanı listenin en başına ekleyebiliriz (https://github.com/VB-CORE/life_client/pull/190)

- [x] 5. Favoriler ekranında 6 tane favori mekan var diyelim, arama yapacağız, birkaç karakter yazdık ve mekanlar filtrelendi, 6 tane mekan varken ekranda sadece filtrelenen mekan kaldı, klavyeyi kapatmadan silme butonuna tıklayınca ekranda hala kalmaya devam ediyor, sanki hiç silme butonuna tıklamamış gibi, arama yapmak için girdiğimiz karakterleri tamamen silince mekanın silindiği belli oluyor (fix: #189)

- [x] 6. Yeni işletme veya yeni burs tale ekranlarında Kvkk metnini açınca En yukarıdaki başlık kırmızı arka planın altında kalıyor, ekranı yakınlaştırınca görünür oluyor (fix: #189)

- [x] 7. İlçe kategori seçimlerindeki dropdown listesini fixed bir size(%70 gibi)ile açmalıyız. Ekranın tamamını kaplıyor, kapatmak için ekranda çok az boşluk kalıyor (fix: #165 / Marketteki versiyon ile test etmişim, bunu done olarak işaretleyebiliriz)

- [x] 8. Evente join basildinga wp otomatik yonlendirme yapilacak (fix: #189)

- [x] 9. Ana sayfa lazy load eklenecek

- [x] 10. Place başvurusunda dropdownlar dummy data kalmış. Gerçek datalar ile güncellenmeli. (fix: #189)

- [x] 11. Detay sayfalarında resimlere tıklayınca görüntüleme ekleyebiliriz. Event detayında yapılan kapak tasarımını görüntülemek güzel olabilir. (fix: #189)

**Comment by VB10** [comment]
1- fıxed

**Comment by VB10** [comment]
2. konu ile alkali soyle yaptim suan o alan aktif ise yani adam izin vermisse opacity vererek disable ettim. he diyecksin adam kapatmak isterse onu gitsin app disindan kendi yapsin dusuncesini buinsenss decide diyorum xd

**Comment by VB10** [comment]
@BerkSartik sabah 5. maddeye bakabilri misin

**Comment by VB10** [comment]
@BerkSartik suan ana sayfa lazy load calismakta projede her yer dinamik o bitti. wp yonlednirmesi yine sende

**Comment by mysCod3r** [comment]
- [x] Favorites ve News sayfaları ilk açılırken shimmer geçene kadar overflow veriyor. (cihaz çözünürlüğü: 1080x2220) (fix: #188)
- [x] Ayarlar sayfasında Uygulama hakkındaya basınca sayfa açılana kadar boş ekran görünüyor. Loading eklenebilir. (fix: #189 )

**Comment by BerkSartik** [comment]
@kadirbekar hocam bu durumun ekran görüntüsünü atabilir misiniz? bulamadım demek istediğinizi o yüzden. Eski request formda bu sorunla karşılaşmış olabilirsiniz diye tahmin ediyorum ama emin olmak istedim.

> 7. İlçe kategori seçimlerindeki dropdown listesini fixed bir size(%70 gibi)ile açmalıyız. Ekranın tamamını kaplıyor, kapatmak için ekranda çok az boşluk kalıyor

**Comment by BerkSartik** [comment]
>  8. Evente join basildinga wp otomatik yonlendirme yapilacak

@VB10 hocam şuan calendar kaydediyoruz o butonda ve bazı etkinliklerde numarayı yazmıyor Samet hoca. Bu yüzden bu task'e çok sıcak bakamıyorum ama seçenek sunup whatsapp ulaş veya takvime ekle seçeneği sunabiliriz. Sadece tarihi unutmamak isteyenlerde olabilir wp için forcelamamalıyız bence.

**Comment by VB10** [comment]
> > 8. Evente join basildinga wp otomatik yonlendirme yapilacak
> 
> @VB10 hocam şuan calendar kaydediyoruz o butonda ve bazı etkinliklerde numarayı yazmıyor Samet hoca. Bu yüzden bu task'e çok sıcak bakamıyorum ama seçenek sunup whatsapp ulaş veya takvime ekle seçeneği sunabiliriz. Sadece tarihi unutmamak isteyenlerde olabilir wp için forcelamamalıyız bence.

katiliyorum mantikli

**Comment by kadirbekar** [comment]
> @kadirbekar hocam bu durumun ekran görüntüsünü atabilir misiniz? bulamadım demek istediğinizi o yüzden. Eski request formda bu sorunla karşılaşmış olabilirsiniz diye tahmin ediyorum ama emin olmak istedim.
> 
> 
> 
> > 7. İlçe kategori seçimlerindeki dropdown listesini fixed bir size(%70 gibi)ile açmalıyız. Ekranın tamamını kaplıyor, kapatmak için ekranda çok az boşluk kalıyor

Bu şekilde tam ekranı kaplıyor @BerkSartik hocam, yükseliği ile oynanabilir diye düşünüyorum.

![image](https://github.com/VB-CORE/life_client/assets/34074484/b1137936-8c8f-41e7-ab4f-5c86f6522c67)

**Comment by BerkSartik** [comment]
@kadirbekar hocam böyle bir dropdown kullanmıyoruz diye biliyorum artık o yüzden hangi sayfada olduğunu bulamıyorum

Mekan Kaydetme sayfasında vardı daha öncesinde o da değişti son prlar ile eski kalmıştı yani

**Comment by kadirbekar** [comment]
> @kadirbekar hocam böyle bir dropdown kullanmıyoruz diye biliyorum artık o yüzden hangi sayfada olduğunu bulamıyorum
> 
> Mekan Kaydetme sayfasında vardı daha öncesinde o da değişti son prlar ile eski kalmıştı yani

@BerkSartik  Hocam burası yeni işletme başvuru ekranında kategori seçimi sırasında açılıyor aslında veya ilçe seçimi yaparken.

**Comment by BerkSartik** [comment]
Yeni işletme talebi sayfasında bottom sheet açıyoruz hocam şuan `release` bakıyorsanız o eski sayfalar o yüzden @kadirbekar 
![Screenshot_1704899742](https://github.com/VB-CORE/life_client/assets/48359825/9d62e1f8-ea81-44e5-be1e-54e054a7202e)

**Comment by kadirbekar** [comment]
> Yeni işletme talebi sayfasında bottom sheet açıyoruz hocam şuan `release` bakıyorsanız o eski sayfalar o yüzden @kadirbekar ![Screenshot_1704899742](https://private-user-images.githubusercontent.com/48359825/295613500-9d62e1f8-ea81-44e5-be1e-54e054a7202e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDAyMjAsIm5iZiI6MTcwNDg5OTkyMCwicGF0aCI6Ii80ODM1OTgyNS8yOTU2MTM1MDAtOWQ2MmUxZjgtZWE4MS00NGU1LWJlMWUtNTRlMDU0YTcyMDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE1MTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NjllYzk3MzQ4MzZlNWRhMThlMDc4M2UxM2E2NWZmNDUzMGQ0NDg0NzgwYmI3MTdhN2ZlMTQzNmRhMjI2ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o2ogcQkXG8L0IvWumKkqzh8jFZ9sYcduCir4t-h0r9M)

Pardon hocam, bildirimleri marketteki uygulama ile test ederken son halini kurmayı unuttum demek ya, o zaman bu maddeyide done olarak işaretleyebiliriz, elinize sağlık

**Comment by BerkSartik** [comment]
@kadirbekar Teşekkürler hocam sizinde elinize sağlık

**Comment by kadirbekar** [comment]
danke hocam @BerkSartik

**Comment by kadirbekar** [comment]
3. madde için bir PR gönderdim hocam @BerkSartik

**Comment by BerkSartik** [comment]
All done eline sağlık herkesin
