### ISSUE TITLE
Bugs, features and improvements V2

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#191]
- [x] 1. Kategori filtre seçim ekranında sağ tarafta gözüken scrollbar ekranın tam genişliğini almıyor, biraz daha solda kalıyor (fix: #192)

- [x] 2. Dil değişikliği yapınca ekranın ortasındaki + iconuna tıklayınca menüdeki başlıkların dil değeri değişmiyor (fix: #192)

- [x] 4. Örnek burs başvurusu yapmayı denedim, bütün bilgileri doldurdum fakat Save butonuna tıkladıktan sonra tepki alamadım. (fix: #193)
-> Loglarda var ise, kadirbekar054@gmail.com, 531 896 76 62 ile başvuru yaptım. İşlem başarılı veya hatalı sonuçlandı ise diyalog, snackbar tarzı mesaj gözükmedi, ekran aynı şekilde kaldı

- [x] 5. Yeni Proje Başvurusu Sayfasında (fix: #193)
a- Her bilgiyi doldurdum, Save butonuna tıkladıktan sonra burs başvurusundaki gibi tepki alamadım     
b- Resim hariç her bilgiyi doldurdum, Save butonuna tıkladıktan sonra resim seçiniz uyarı mesajı geldi (Bilgi amaçlı yazıyorum) 
c- İşlem başarılı veya hatalı sonuçlandı ise diyalog, snackbar tarzı mesaj gözükmedi, ekran aynı şekilde kaldı

- [x] 6. Yeni İşletme Başvurusu Sayfasında (fix: #193)
a- Her bilgiyi doldurdum, Save butonuna tıkladıktan sonra burs başvurusundaki gibi tepki alamadım
b- Resim hariç her bilgiyi doldurdum, Save butonuna tıkladım fakat yeni proje başvurusundaki gibi resim seçiniz uyarısı gelmedi
c- İşlem başarılı veya hatalı sonuçlandı ise diyalog, snackbar tarzı mesaj gözükmedi, ekran aynı şekilde kaldı

- [x] 7. Klavye açıkken ekranda boş bir yere tıklayınca kapanmasını ekleyebiliriz, form ekranlarında çok kolaylık sağlayacaktır (fix: #192)

**Comment by mysCod3r** [comment]
Favoriler:
- [x] Bir dükkana gidince geri gelmek yerine ana sayfaya atıyor. 
- [x] Tümünü temizle butonuna basar basmaz herşeyi uçuruyor. Burda bir emin misiniz dialog açılabilir.  fix(#199)

Search:
- [x] Boş string ile arama yapılabiliyor. Trim atılmalı. 
- [x] Arama butonunun sağındaki çarpı iconu çöp icon ile değişebilir. Çarpı olunca searchten çıkmak gibi algılanabilir. Ve UI olarak search bar ile eşit hizada değil. (Center olsa daha güzel duracaktır yada searchbar ın height ı kısılabilir)


Filtre:
- [x] Kategori isimlerinde localize yok. (Konuşulmalı yapılacak mı diye..) (Şimdilik done ileride eklenebilir)

 
Request proje:
- [x] Date seçmeye basıp iptal edince yine de okayliyor.   fix(#199)


Settings:
- [x] Tüm tile lar genişletilince uygulamayı değerlendirin kısmı navbar altında kalıyor. Ben oraya navbar yüksekliği kadar sizedbox atmıştım ama iphone da alttan uygulama çubugu olduğu için safearea gerekli sanırım.

**Comment by kadirbekar** [comment]
- [x] 1- Campaings view içerisinde listelenen bir itemın detayını açıyoruz. En alttaki seçenekleri görüntüle - Whatsappten mesaj gönder dedikten sonra gönderilen mesaj "String of extension olarak gönderiliyor"

(Başka bir bulgu olursa burayı editleyeceğim)
